"""
sparcli
=======

Styled CLI output and interactive input widgets, built directly on ANSI escape
codes with no third-party dependencies.

The public API is re-exported flat from this package: import widgets and types
directly (``from sparcli import Panel, TextInput``). Grouped helpers stay
reachable as submodules (``sparcli.width``, ``sparcli.terminal``,
``sparcli.markup``).
"""

from sparcli.core import (
    DEFAULT_ACCENT,
    Align,
    Attribute,
    BorderChars,
    BorderType,
    Color,
    ColorName,
    ColorSupport,
    Edges,
    Line,
    Modifier,
    Position,
    Renderable,
    Rendered,
    Span,
    Style,
    Text,
    Theme,
    Title,
    VAlign,
    color_support,
    into_line,
    into_span,
    into_text,
    is_input_tty,
    is_output_tty,
    set_theme,
    term_height,
    term_width,
    terminal_size,
    theme,
)
from sparcli.core import markup as markup
from sparcli.core import terminal as terminal
from sparcli.core import width as width
from sparcli.errors import (
    ConfigError,
    NoTerminalError,
    SparcliError,
    TerminalError,
)
from sparcli.input import (
    Confirm,
    DatePicker,
    FuzzySelect,
    History,
    NumberInput,
    Outcome,
    OutcomeKind,
    PasswordInput,
    Select,
    Shortcut,
    Textarea,
    TextInput,
    edit_file,
)
from sparcli.input import event as event
from sparcli.input import shortcut as shortcut
from sparcli.input import validate as validate
from sparcli.output import (
    Alert,
    AlertKind,
    Badge,
    Cell,
    Column,
    Columns,
    Diff,
    KeyValue,
    List,
    Live,
    Marker,
    MultiProgress,
    Pager,
    Panel,
    ProgressBar,
    ProgressStyle,
    Rule,
    Spinner,
    SpinnerStyle,
    Table,
    Thresholds,
    Tree,
    TreeNode,
    align,
    pad,
    vstack,
)

__all__ = [
    "DEFAULT_ACCENT",
    "Alert",
    "AlertKind",
    "Align",
    "Attribute",
    "Badge",
    "BorderChars",
    "BorderType",
    "Cell",
    "Color",
    "ColorName",
    "ColorSupport",
    "Column",
    "Columns",
    "ConfigError",
    "Confirm",
    "DatePicker",
    "Diff",
    "Edges",
    "FuzzySelect",
    "History",
    "KeyValue",
    "Line",
    "List",
    "Live",
    "Marker",
    "Modifier",
    "MultiProgress",
    "NoTerminalError",
    "NumberInput",
    "Outcome",
    "OutcomeKind",
    "Pager",
    "Panel",
    "PasswordInput",
    "Position",
    "ProgressBar",
    "ProgressStyle",
    "Renderable",
    "Rendered",
    "Rule",
    "Select",
    "Shortcut",
    "Span",
    "SparcliError",
    "Spinner",
    "SpinnerStyle",
    "Style",
    "Table",
    "TerminalError",
    "Text",
    "TextInput",
    "Textarea",
    "Theme",
    "Thresholds",
    "Title",
    "Tree",
    "TreeNode",
    "VAlign",
    "align",
    "color_support",
    "edit_file",
    "event",
    "into_line",
    "into_span",
    "into_text",
    "is_input_tty",
    "is_output_tty",
    "markup",
    "pad",
    "set_theme",
    "shortcut",
    "term_height",
    "term_width",
    "terminal",
    "terminal_size",
    "theme",
    "validate",
    "vstack",
    "width",
]
